# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: 'myimage'
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      inputs:
        containerRegistry: 'aqua_registry_with_login'
        command: 'login'


    - task: aquasecScanner@4
      inputs:
        image: 'myimage'
        scanType: 'hosted'
        register: false
        hideBase: false
        showNegligible: false
        windowsScannerVersion: '4.2.0'
        connection: 'Aqua_3'
        caCertificates: true